// <!-- ---- Bismillah ---- -->
export const sneakers = [
  {
    id: 1,
    name: "Мужские Кроссовки Nike Blazer Mid Suede",
    image: "./assets/image 5-1.png",
    price: "12 999 руб.",
    isLiked: false,
  },
  {
    id: 2,
    name: "Мужские Кроссовки Nike Air Max 270",
    image: "./assets/image 5-2.png",
    price: "12 999 руб.",
    isLiked: false,
  },
  {
    id: 3,
    name: "Мужские Кроссовки Nike Blazer Mid Suede",
    image: "./assets/image 5-3.png",
    price: "8 499 руб.",
    isLiked: false,
  },
  {
    id: 4,
    name: "Кроссовки Puma X Aka Boku Future Rider",
    image: "./assets/image 5-4.png",
    price: "8 999 руб.",
    isLiked: false,
  },
  {
    id: 5,
    name: "Мужские Кроссовки Under Armour Curry 8",
    image: "./assets/image 5-5.png",
    price: "15 199 руб.",
    isLiked: false,
  },
  {
    id: 6,
    name: "Мужские Кроссовки Nike Kyrie 7",
    image: "./assets/image 5-6.png",
    price: "11 299 руб.",
    isLiked: false,
  },
  {
    id: 7,
    name: "Мужские Кроссовки Under Armour Curry 8",
    image: "./assets/image 5-7.png",
    price: "15 199 руб.",
    isLiked: false,
  },
  {
    id: 8,
    name: "Мужские Кроссовки Jordan Air Jordan 11",
    image: "./assets/image 5-8.png",
    price: "10 799 руб.",
    isLiked: false,
  },
  {
    id: 9,
    name: "Мужские Кроссовки Nike LeBron XVIII",
    image: "./assets/image 5-9.png",
    price: "16 499 руб.",
    isLiked: false,
  },
  {
    id: 10,
    name: "Мужские Кроссовки Nike Lebron XVIII Low",
    image: "./assets/image 5-10.png",
    price: "13 999 руб.",
    isLiked: false,
  },
  {
    id: 11,
    name: "Мужские Кроссовки Nike Blazer Mid Suede",
    image: "./assets/image 5-11.png",
    price: "8 499 руб.",
    isLiked: false,
  },
  {
    id: 12,
    name: "Кроссовки Puma X Aka Boku Future Riderv",
    image: "./assets/image 5.png",
    price: "11 299 руб.",
    isLiked: false,
  },
];
